NO_MESSAGES = "There are no messages to read/reply to! :frowning: Check again later!"
NO_REQUESTS = "You haven't sent out any messages to receive responses! :confused:"
BAD_MESSAGE_REF = ":no_entry: Could not find the message you replied to."
INVALID_COMMAND = ":no_entry: Invalid command"
GET_MSG_REQ_CMD = "read"
RETRIEVE_MY_MSGS_CMD = "responses"
COMMAND_PREFIX = '/'
SUCCESS_EMOJI = "✅"
REJECT_MESSAGE = ":x: Your message has been rejected!"
